version: "3.8" 
services:
    db:
        container_name: timescaledb
        image: timescale/timescaledb:latest-pg13
        ports: 
         - "5432:5432"
        environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=root
        volumes:
            - /timescaledbdocker/data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./DB_CONF/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    graphing:
        container_name: grafana
        image: grafana/grafana
        ports: 
         - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=grafana
        depends_on:
         - db
        volumes:
            - ./grafana:/etc/grafana/provisioning/datasources
    server:
        container_name: tracker-server
        image: dioben/nntrackerua-server:latest
        ports: 
         - "8000:8000"
        depends_on:
         - db
    deployer:
        container_name: tracker-deployer
        image: dioben/nntrackerua-deployer:latest
        ports: 
         - "7000:7000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    parser:
        container_name: tracker-parser
        image: dioben/nntrackerua-parser:latest
        ports: 
         - "6000:6000"
    celery_broker:
        container_name: redis
        image: redis:latest
        ports:
         - "6379:6379"
