# Generated by Django 3.2 on 2021-05-05 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.TextField()),
                ('isdone', models.BooleanField()),
                ('isrunning', models.BooleanField()),
                ('biases', models.BinaryField()),
                ('epoch_interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goal_epochs', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Simulations',
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('epoch', models.IntegerField()),
                ('layer', models.IntegerField()),
                ('weight', models.BinaryField()),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'Weights',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'Updates',
            },
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'Tags',
                'unique_together': {('tag', 'sim')},
            },
        ),
    ]
