# Generated by Django 3.2 on 2021-05-26 21:57

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.TextField()),
                ('learning_rate', models.FloatField()),
                ('isdone', models.BooleanField()),
                ('isrunning', models.BooleanField()),
                ('biases', models.BinaryField()),
                ('layers', models.IntegerField()),
                ('epoch_interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('goal_epochs', models.IntegerField()),
                ('metrics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulations',
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('epoch', models.IntegerField()),
                ('layer_index', models.IntegerField()),
                ('layer_name', models.CharField(max_length=150)),
                ('weight', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'weights',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'epoch_values',
            },
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('iskfold', models.BooleanField(default=False)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
                ('tagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ExtraMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('epoch', models.IntegerField()),
                ('value', models.FloatField()),
                ('metric', models.CharField(max_length=60)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulation')),
            ],
            options={
                'db_table': 'extra_metrics',
            },
        ),
        migrations.AddIndex(
            model_name='weights',
            index=models.Index(fields=['sim', 'epoch'], name='weights_sim_id_5dcd13_idx'),
        ),
        migrations.AddIndex(
            model_name='weights',
            index=models.Index(fields=['sim', 'layer_index'], name='weights_sim_id_11ee55_idx'),
        ),
        migrations.AddIndex(
            model_name='update',
            index=models.Index(fields=['sim', 'epoch'], name='epoch_value_sim_id_c134a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tagged',
            index=models.Index(fields=['tag'], name='Tags_tag_d28204_idx'),
        ),
        migrations.AddIndex(
            model_name='tagged',
            index=models.Index(fields=['tagger'], name='Tags_tagger__49a09e_idx'),
        ),
        migrations.AddIndex(
            model_name='tagged',
            index=models.Index(fields=['sim'], name='Tags_sim_id_e19bb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagged',
            unique_together={('tag', 'sim')},
        ),
        migrations.AddIndex(
            model_name='extrametrics',
            index=models.Index(fields=['sim', 'epoch'], name='extra_metri_sim_id_8ce75e_idx'),
        ),
        migrations.AddIndex(
            model_name='extrametrics',
            index=models.Index(fields=['sim', 'metric'], name='extra_metri_sim_id_d0fdc4_idx'),
        ),
    ]
